name: Power BI Scan
on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tabular Editor CLI
        run: dotnet tool install --global TabularEditor.2.CLI

      - name: Run Best Practice Analyzer
        shell: pwsh
        run: |
          # Buscamos la carpeta del modelo
          $model = (Get-ChildItem -Directory -Filter "*.SemanticModel" | Select-Object -First 1).FullName
          
          # El comando 'te2' se instala con el paso anterior
          # Usamos --rules para descargar las reglas de Microsoft directamente
          te2 "$model" -B "https://githubusercontent.com" -V
